Меняй-удаляй (часть 1)
htmlacademy-ecmascript/1655243-cinemaddict-13 pull request #12
Opened 2021-01-03 14:11 UTC by VladislavYusupov

2021-01-08 16:11 UTC, olegsklyarov requested changes
В целом все хорошо, нужно только исправить несколько минорные замечаний.

2021-01-08 16:11 UTC, olegsklyarov commented on src/presenter/film-list.js
>  import FilmsView from "../view/films";
Внутри `view/films.js` нужно переименовать класс в `Films`

2021-01-08 16:11 UTC, olegsklyarov commented on src/view/popup.js
>  import SmartView from "./smart";
Сделать одинаковыми названия модуля `popup-comment-emoji.js` и класса `EmojiImage`

2021-01-08 16:11 UTC, olegsklyarov commented on src/const.js
> +  MINOR: `MINOR`,
Предлагаю сделать более понятные названия типов обновления. Если `PATCH` более-менее понятен, то `MINOR` / `MAJOR` совсем не ясны. Насколько я понял по коду, `MAJOR` — это когда из DOM удаляются все фильмы и перерисовываются заново. Если так, то подходящее название `removeFromDomAndRerender` или что-то подобное.

2021-01-09 14:50 UTC, VladislavYusupov commented on src/view/film-card.js
> +
Прошелся по файлам, поправил названия

2021-01-09 14:59 UTC, VladislavYusupov commented on src/const.js
> +  MINOR: `MINOR`,
Да, согласен. В настоящий момент PATCH использовался только в одном случае - если нам было необходимо заново инициализировать отдельно взятый фильм, поэтому переименовал на RERENDER_SINGLE_LIST_ITEM.
MINOR - для новой отрисовки с сохранением текущего количества фильмов и типа сортировки (переименовал на RERENDER_WITH_CURRENT_PRESENTER_SETTINGS, вроде название близкое по смыслу).
MAJOR - для новой отрисовки с значением текущего количества фильмов и типа сортировки по умолчанию (переименовал на RERENDER_WITH_DEFAULT_PRESENTER_SETTINGS).

2021-01-10 17:38 UTC, merged