Шаблонизируй это
htmlacademy-ecmascript/1655243-cinemaddict-13 pull request #4
Opened 2020-12-06 17:17 UTC by VladislavYusupov

2020-12-07 11:58 UTC, olegsklyarov requested changes
В целом хорошо! Но есть несколько моментов для доработки, в том числе нарушаются некоторые критерии. Перечитай их пожалуйста и держи постоянно в голове когда пишешь код :-)

2020-12-07 11:58 UTC, olegsklyarov commented on src/helpers/mockGenerateHelper.js
> +  const lower = Math.ceil(Math.min(a, b));
1. Лучше назвать файл getRandomInteger, текущее название слишком общее.
2. Функцию лучше упростить:
```
const getRandomInteger = (minValue, maxValue) => Math.floor(minValue + Math.random() * (maxValue - minValue + 1));
```

2020-12-07 11:58 UTC, olegsklyarov commented on src/mock/comment.js
> +  return messages[getRandomInteger(0, messages.length - 1)];
Напрашивается функция `getArrayRandomElement = (arr) => { ... }`

2020-12-07 11:58 UTC, olegsklyarov commented on src/mock/comment.js
> +  const messages = [
Константу выносим из функции в начало файла (есть критерий на это)

2020-12-07 11:58 UTC, olegsklyarov commented on src/mock/common.js
> +import getRandomInteger from "../helpers/mockGenerateHelper";
Название файла уточним до `title.js` например

2020-12-07 11:58 UTC, olegsklyarov commented on src/mock/film.js
> +  return (Math.random() * MAX_RATING).toFixed(FRACTIONAL_CHARACTERS_NUMBER_IN_RATING);
Напрашивается функция `const getRandomPositiveInt = (maxValue) => {...}`

2020-12-07 11:58 UTC, olegsklyarov commented on src/mock/user.js
> +  const titlesCount = getRandomInteger(0, MAX_TITLES_COUNT);
`getRandomPositiveInt`

2020-12-07 11:58 UTC, olegsklyarov commented on src/view/film-card.js
> +  const limitDescription = (text) => {
Эту функцию нужно вынести из View слоя. Например в helpers

2020-12-07 11:58 UTC, olegsklyarov commented on src/view/popup.js
> +const createComments = (comments) => {
Логику сборки из нескольких шаблонов нужно вынести из слоя View, положить где-то рядом в main.js

2020-12-08 17:58 UTC, VladislavYusupov commented on src/helpers/mockGenerateHelper.js
> +  const lower = Math.ceil(Math.min(a, b));
Изменил на упрощенную функцию

2020-12-08 17:59 UTC, VladislavYusupov commented on src/mock/comment.js
> +  return messages[getRandomInteger(0, messages.length - 1)];
Вынес в helpers/getArrayRandomElement

2020-12-08 18:00 UTC, VladislavYusupov commented on src/mock/comment.js
> +  const messages = [
Вынес константы в начало файла

2020-12-08 18:00 UTC, VladislavYusupov commented on src/mock/common.js
> +import getRandomInteger from "../helpers/mockGenerateHelper";
скорректировал название файла

2020-12-08 18:00 UTC, VladislavYusupov commented on src/mock/film.js
> +  return (Math.random() * MAX_RATING).toFixed(FRACTIONAL_CHARACTERS_NUMBER_IN_RATING);
Добавил функцию в helpers/getRandomPositiveInt

2020-12-08 18:01 UTC, VladislavYusupov commented on src/mock/user.js
> +  const titlesCount = getRandomInteger(0, MAX_TITLES_COUNT);
Заменил

2020-12-08 18:01 UTC, VladislavYusupov commented on src/view/film-card.js
> +  const limitDescription = (text) => {
Вынес как отдельное поле фильма (film.shortDescription)

2020-12-08 18:01 UTC, VladislavYusupov commented on src/view/popup.js
> +const createComments = (comments) => {
Вынес

2020-12-10 09:03 UTC, olegsklyarov requested changes
Молодец, проделал большую работу! Еще несколько моментов поправить и можно двигаться дальше.

2020-12-10 09:03 UTC, olegsklyarov commented on src/createPopupElement.js
> +  for (let element of elements) {
`const` вместо `let`

2020-12-10 09:03 UTC, olegsklyarov commented on src/main.js
> +const films = new Array(filmListOptions.main.maxCount).fill().map(generateFilm);
У fill должен быть хотя бы один аргумент, [проверь доки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/fill)

2020-12-10 09:03 UTC, olegsklyarov commented on src/mock/comment.js
> +    .fill()
У fill должен быть хотя бы один аргумент, [проверь доки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/fill)

2020-12-11 04:09 UTC, VladislavYusupov commented on src/helpers/getArrayRandomElements.js
> +    let elementNumber = getRandomPositiveInt(arr.length - 1);
Изменил реализацию на использование getArrayRandomElement

2020-12-11 04:10 UTC, VladislavYusupov commented on src/mock/comment.js
> +const messages = [
Подправил

2020-12-11 04:10 UTC, VladislavYusupov commented on src/createPopupElement.js
> +  for (let element of elements) {
Исправил

2020-12-11 04:12 UTC, VladislavYusupov commented on src/main.js
> +const films = new Array(filmListOptions.main.maxCount).fill().map(generateFilm);
Заполнил пустыми объектами - fill({})

2020-12-11 04:12 UTC, VladislavYusupov commented on src/mock/comment.js
> +    .fill()
Заполнил пустыми объектами - fill({})

2020-12-11 04:20 UTC, merged