Большие перемены (часть 2)
htmlacademy-ecmascript/1655243-cinemaddict-13 pull request #9
Opened 2020-12-25 16:01 UTC by VladislavYusupov

2020-12-28 16:08 UTC, olegsklyarov requested changes

2020-12-28 16:08 UTC, olegsklyarov commented on src/helpers/getRandomDate.js
> +  return dayjs(new Date(randomYear, randomMonth, randomDay));
Лучше использовать [конструктор из объекта](https://day.js.org/docs/en/parse/object), тогда будет без промежуточного объекта `Date` (это чуть оптимальнее)

2020-12-28 16:08 UTC, olegsklyarov commented on src/view/popup-comment.js
> +          <span class="film-details__comment-day">${dayjs(date).format(`YYYY/M/D HH:mm`)}</span>
Формат `YYYY/M/D HH:mm` нужно вынести в константу. Можно в начало файла, либо вынести куда-то выше, т.к. такой формат может использоваться где-то еще по проекту.

2020-12-28 16:08 UTC, olegsklyarov commented on src/view/popup.js
> +                  <td class="film-details__cell">${dayjs(releaseDate).format(`D MMMM YYYY`)}</td>
Формат вынести в константу. Это ОК, что в разных местах разный формат даты? Кажется нужно использовать одинаковый.

2020-12-29 05:36 UTC, VladislavYusupov commented on src/helpers/getRandomDate.js
> +  const randomDay = getRandomInteger(MIN_DAY, dayjs(randomMonth).daysInMonth());
Сделал через объект

2020-12-29 05:36 UTC, VladislavYusupov commented on src/helpers/getRandomDate.js
> +  return dayjs(new Date(randomYear, randomMonth, randomDay));
Поправил

2020-12-29 05:37 UTC, VladislavYusupov commented on src/view/popup-comment.js
> +          <span class="film-details__comment-day">${dayjs(date).format(`YYYY/M/D HH:mm`)}</span>
Вынес в константу в файл const.js

2020-12-29 05:38 UTC, VladislavYusupov commented on src/view/popup.js
> +                  <td class="film-details__cell">${dayjs(releaseDate).format(`D MMMM YYYY`)}</td>
Вынес в константу в файл const.js. Да, судя по верстке разные форматы.

2020-12-29 05:55 UTC, merged